<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MonkyHomie" failures="1" tests="2" name="Test" time="37.257" errors="0" timestamp="2023-05-04T11:57:13 IST">
  <testcase classname="day10.Task4and5" name="Case1" time="6.688"/>
  <testcase classname="day10.Task4and5" name="Case2" time="6.446">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index]
at day10.Task4and5.Case2(Task4and5.java:93)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Case2 -->
</testsuite> <!-- Test -->
